apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "mysession"
    traefik.ingress.kubernetes.io/session-cookie-secure: "true"
    traefik.ingress.kubernetes.io/session-cookie-samesite: "None"
    traefik.ingress.kubernetes.io/forwarded-headers-trusted-ip: "10.10.29.217, 10.10.29.219"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp
            port:
              number: 3000
