
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer if needed
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: webapp
